name: Contract Tests

on:
  workflow_call:
  pull_request:
    paths:
      - 'contracts/**'
      - '.github/workflows/contracts-test.yaml'
  workflow_dispatch:

jobs:
  contract-tests:
    name: Contract Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          cd contracts
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          cd contracts
          forge test -vvv
        id: test